name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: build
      uses: actions/setup-node@v2
      with:
        node-version: '10.16'
    - run: |
        yarn
        yarn build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist