name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: build
      uses: actions/setup-node@v2
      with:
        node-version: '10.16'
    - run: |
        yarn
        yarn build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./dist